name: flutter_link_previewer
description: >
  Customizable link and URL preview extracted from the
  provided text with the ability to render from the cache. Ideal
  for chat applications.
version: 3.2.2
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_link_previewer

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_chat_types: ^3.6.2
  html: ^0.15.4
  url_launcher: ^6.3.1
  
dependency_overrides:
  uuid: ^3.0.7
  http: ^1.2.2
  file: ^7.0.0

dev_dependencies:
  #dart_code_metrics: ^5.7.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
